services:
  smf:
    build: smf
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smf.rule=Host(`smf.app.example`)"
      - "traefik.http.routers.smf.tls=true"
      - "traefik.http.middlewares.smf.headers.contentSecurityPolicy=frame-src 'self' *;"

  setup:
    build: setup
    links:
      - smf
    depends_on:
      - smf
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - SMF_HOST=smf
      - SMF_PUBLIC_URL=${SMF_PUBLIC_URL:-https://smf.app.example}

  db:
    image: mariadb:10.7.3-focal
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD:-password}
      - UPLOAD_LIMIT=300M
    links:
      - db
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`pma.app.example`)"
      - "traefik.http.routers.pma.tls=true"

  reverse-proxy:
    image: traefik:v2.4.7
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./traefik/dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml:ro
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./certs:/etc/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db-data:
