version: '3'
services:
  smf:
    build: smf
    ports:
      - "80:80"
    depends_on:
      - db

  setup:
    build: setup
    links:
      - smf
    depends_on:
      - smf
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - SMF_HOST=smf
      - SMF_PUBLIC_URL=${SMF_PUBLIC_URL:-http://localhost}

  db:
    image: mariadb:10.7.3-focal
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD:-password}
    links:
      - db
    depends_on:
      - db

volumes:
  db-data:
