http:
  routers:
    traefik:
      rule: "Host(`traefik.app.example`)"
      service: "api@internal"
      tls:
        domains:
          - main: "example"
            sans:
              - "*.example"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
